### ISSUE TITLE
LazyAssertion chaining no longer hinted in PhpStorm

### ISSUE THREAD

**Issue by Vorta** [beberlei/assert#291]
Version: v3.2.2
I'm not sure if this is due to PhpStorm or due to LazyAssertion docblock, so I'm reporting here first.

Code example:
```
Assert::lazy()
    ->that($something, null)
    ->notNull('error')
    ->notEmpty('error')
    ->numeric('error')
    ->verifyNow();
```

Above example will work normally, however, PhpStorm will underline the `notEmpty` method and say "Method 'notEmpty' not found".

The only way I could get the hints to work properly again was to replace `@method $this ...` with `@method \Assert\LazyAssertion` inside the LazyAssertion.php.

**Comment by rquadling** [comment]
That looks like an error on our part.

**Comment by rquadling** [comment]
Hopefully fixed in v.3.2.4.

**Comment by LucasHantz** [comment]
Hello, looks like it's not fixed.
The "@method static static" does not the trick.
Putting @method LazyAssertion works though. Why not use that?

**Comment by rquadling** [comment]
Fair enough!

**Comment by rquadling** [comment]
Released 3.2.7
